# Generated by Django 5.2.11 on 2026-02-23 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='profiles_users',
        ),
    ]
