# Generated by Django 5.2.11 on 2026-02-23 15:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compendium', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(default='default_character.jpg', upload_to='characters_pics')),
                ('name', models.CharField(max_length=300)),
                ('world_view', models.TextField()),
                ('health', models.IntegerField()),
                ('weapon', models.CharField(max_length=150)),
                ('armor', models.CharField(max_length=150)),
                ('protection', models.IntegerField()),
                ('backstory', models.TextField()),
                ('inventory', models.TextField(blank=True)),
                ('charisma', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('bodytype', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('power', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='compendium.charactersclass')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='compendium.races')),
                ('spells', models.ManyToManyField(related_name='characters', to='compendium.spells')),
            ],
        ),
    ]
