# Generated by Django 5.2.11 on 2026-02-23 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characters',
            options={'verbose_name': 'character', 'verbose_name_plural': 'characters'},
        ),
        migrations.AlterModelTable(
            name='characters',
            table='characters',
        ),
    ]
