# Generated by Django 5.2.11 on 2026-02-23 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compendium', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charactersclass',
            options={'ordering': ['name'], 'verbose_name': 'character class', 'verbose_name_plural': 'characters classes'},
        ),
        migrations.AlterModelOptions(
            name='monsters',
            options={'ordering': ['name'], 'verbose_name': 'monster', 'verbose_name_plural': 'monsters'},
        ),
        migrations.AlterModelOptions(
            name='races',
            options={'ordering': ['name'], 'verbose_name': 'race', 'verbose_name_plural': 'races'},
        ),
        migrations.AlterModelOptions(
            name='spells',
            options={'ordering': ['level', 'name'], 'verbose_name': 'spell', 'verbose_name_plural': 'spells'},
        ),
        migrations.AlterModelTable(
            name='charactersclass',
            table='characters_classes',
        ),
        migrations.AlterModelTable(
            name='monsters',
            table='monsters',
        ),
        migrations.AlterModelTable(
            name='races',
            table='races',
        ),
        migrations.AlterModelTable(
            name='spells',
            table='spells',
        ),
    ]
